server:
  port: 8000

spring:
  application:
    name: cambio-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: admin
      username: samuelnfavero@gmail.com
      password: mongo123
      authentication-database: admin
