server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cambio-service

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: admin
#      username: samuelnfavero@gmail.com
#      password: mongo123
#      authentication-database: admin

  datasource:
    url: jdbc:postgresql://postgres-compose:5432/cambio-service
    username: postgres
    password: postgres123
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



  flyway:
    url: jdbc:postgresql://postgres-compose:5432/cambio-service
    schemas: public
    user: postgres
    password: postgres123
    locations: classpath:db/migration

