server:
  port: 8000

spring:
  application:
    name: cambio-service

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: admin
#      username: samuelnfavero@gmail.com
#      password: mongo123
#      authentication-database: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123
    hikari:
      schema: migrations
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



  flyway:
    url: jdbc:postgresql://localhost:5432/
    schemas: postgres
    user: postgres
    password: postgres123

