server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: cambio-service

  boot:
    admin:
      client:
        url: http://localhost:8888

#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: admin
#      username: samuelnfavero@gmail.com
#      password: mongo123
#      authentication-database: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/cambio-service
    username: postgres
    password: postgres123
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect



  flyway:
    url: jdbc:postgresql://localhost:5432/cambio-service
    schemas: public
    user: postgres
    password: postgres123
    locations: classpath:db/migration

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: false
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  management:
    metrics:
      tags:
        application=${spring:application:name}:
